charts/sophora-export-job/Chart.yaml, charts/sophora-export-job/values.yaml, charts/sophora-import-job/Chart.yaml, charts/sophora-import-job/values.yaml
Sometimes, alerts triggered by Prometheus do not have the correct namespace or no namespace at all.
This PR adds an explicit label "namespace" to the PrometheusRules of `sophora-export-job` and `sophora-import-job`.
=> Add label "namespace" to PrometheusRule

charts/sophora-schema-docs/Chart.yaml, charts/sophora-schema-docs/values.yaml
This PR changes the chart for Schema Docs to use ClusterIP again instead of NodePort.
=> schema-docs: use ClusterIP instead of NodePort

charts/sophora-schema-docs/Chart.yaml, charts/sophora-schema-docs/templates/service.yaml
This PR fixes the service definition for Schema Docs so that it uses the correct values for the service's port.
=> schema-docs: use correct values for service port again

charts/sophora-image-ai/.helmignore, charts/sophora-image-ai/Chart.yaml, charts/sophora-image-ai/README.md, charts/sophora-image-ai/templates/_helpers.tpl, charts/sophora-image-ai/templates/configmap.yaml, charts/sophora-image-ai/templates/deployment.yaml, charts/sophora-image-ai/templates/extra-list.yaml, charts/sophora-image-ai/templates/ingress.yaml, charts/sophora-image-ai/templates/service.yaml, charts/sophora-image-ai/test-values.yaml, charts/sophora-image-ai/values.yaml
This PR adds a new chart for Sophora Image AI.
=> add Sophora Image AI

.github/workflows/release-chart.yml
Prevent job to run in forks
See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
=> Only run job "release" in "subshell/helm-charts"

charts/sophora-image-ai/Chart.yaml, charts/sophora-image-ai/templates/deployment.yaml
This PR fixes a bug in the Helm chart for Sophora Image AI where the configuration inside the container was mounted at an incorrect location.
=> [sophora-image-ai] mount configuration in the correct location

charts/sophora-schema-docs/Chart.yaml, charts/sophora-schema-docs/templates/deployment.yaml
This PR fixes a bug in the Helm chart for Sophora Schema Docs where the configuration inside the container was mounted at an incorrect location.
=> [sophora-schema-docs] mount configuration at the correct location

charts/sophora-image-ai/Chart.yaml, charts/sophora-image-ai/templates/deployment.yaml, charts/sophora-image-ai/values.yaml
This PR is a followup on #99 to mount the configuration inside the container at the correct location for earlier versions of the app.
=> [sophora-image-ai] mount configuration at the correct location for earlier app versions

charts/sophora-schema-docs/Chart.yaml, charts/sophora-schema-docs/templates/deployment.yaml, charts/sophora-schema-docs/values.yaml
This PR is a followup on #100 to mount the configuration inside the container at the correct location for earlier versions of the app.
=> [sophora-schema-docs] mount configuration at the correct location for earlier app versions

charts/sophora-linkchecker/Chart.yaml, charts/sophora-linkchecker/values.yaml
The configuration prefix used by the Linkchecker application is "link-checker".
=> [linkchecker] fixed placeholder key in application.yaml

charts/sophora-server/Chart.yaml, charts/sophora-server/README.md, charts/sophora-server/templates/grpc-ingress.yaml, charts/sophora-server/test-values.yaml, charts/sophora-server/values.yaml
This adds an option to the Server Helm Chart that allows deploying a second ingress to configure gRPC connections. Using this may be necessary starting with Sophora Server v6, which adds a gRPC API.
=> [sophora-server] add grpc ingress option

charts/sophora-importer/Chart.yaml, charts/sophora-importer/values.yaml
Relates to UNSOI-2211.
Spring 6 uses logback-classic 1.4.14 which no longer supports the context variable `event` and causes the application to fail on startup. 
Similar to the Spring 6 Update in sophora-importer, we change the filter to `<turboFilter>`. 
This chart's appVersion is set to `4.11.0` and doesn't need to be updated because the sophora-importer 4.11.0 uses logback-classic 1.2.12 which already contains `ch.qos.logback.classic.turbo.MarkerFilter` for the turboFilter.
=> [sophora-importer] update logback configuration for Spring 6 compatibility

charts/sophora-cluster-common/Chart.yaml, charts/sophora-cluster-common/templates/alerts/prometheusrule.yaml, charts/sophora-server/Chart.yaml, charts/sophora-server/templates/prometheusrule.yaml
Sometimes, alerts triggered by Prometheus do not have the correct namespace or no namespace at all.
This PR adds an explicit label "namespace" to the PrometheusRules of `sophora-server` and `sophora-cluster-common`.
See #38.
=> [sophora-server] [sophora-cluster-common] Add label "namespace" to PrometheusRules

charts/sophora-importer/Chart.yaml, charts/sophora-importer/README.md, charts/sophora-importer/templates/statefulset.yaml, charts/sophora-importer/test-values.yaml, charts/sophora-importer/values.yaml
=> [sophora-importer] support for native s3 connection

charts/sophora-ugc/CHANGELOG.md, charts/sophora-ugc/Chart.yaml, charts/sophora-ugc/templates/_helpers.tpl, charts/sophora-ugc/templates/serviceaccount.yaml, charts/sophora-ugc/test-values.yaml, charts/sophora-ugc/values.yaml
This adds service accounts to be used e.g. in conjunction with db-sidecars for accessing the database
=> [sophora-ugc] UNSO-1979: add support for service accounts

charts/external-secrets/Chart.yaml, charts/external-secrets/README.md, charts/external-secrets/templates/external_secret.yaml
see https://github.com/external-secrets/external-secrets/releases/tag/v0.17.0
=> external-secrets: Update API for externals-secrets >= v0.16.0

charts/sophora-ai/Chart.yaml, charts/sophora-ai/templates/configmap.yaml, charts/sophora-ai/test-values.yaml, charts/sophora-ai/values.yaml
This PR adds configuration support for the Proofread feature which has been added to Sophora AI.
Note: Although this new part of the configuration is actually required to run Sophora AI, the chart will support it as optional to allow running older app versions. This way, users of the chart will not need to change their configuration as long as they are not upgrading the app version.
=> [sophora-ai] add configuration for Proofread feature

charts/sophora-ai/Chart.yaml, charts/sophora-ai/templates/deployment.yaml, charts/sophora-ai/test-values.yaml, charts/sophora-ai/values.yaml
This PR adds support for [Google Application Default Credentials (ADC)](https://cloud.google.com/docs/authentication/application-default-credentials?hl=en).
It is now optional to use a secret that contains the credentials file. Before, the chart required to configure a secret name.
The chart's major version has been bumped to reflect this breaking change.
This PR mirrors the changes made in #190, but for sophora-ai.
=> [sophora-ai] add support for Google ADC

charts/sophora-image-ai/Chart.yaml, charts/sophora-image-ai/templates/_helpers.tpl, charts/sophora-image-ai/templates/deployment.yaml, charts/sophora-image-ai/templates/serviceaccount.yaml, charts/sophora-image-ai/test-values.yaml, charts/sophora-image-ai/values.yaml
This PR adds the functionality necessary to use a service account when deploying Sophora Image AI.
=> [sophora-image-ai] enable use of a service account

charts/sophora-image-access-service/Chart.yaml, charts/sophora-image-access-service/templates/deployment.yaml, charts/sophora-image-access-service/templates/ingress.yaml, charts/sophora-image-access-service/templates/servicemonitor.yaml, charts/sophora-image-access-service/tests/ingresses_test.yaml
1. The new `metrics` port has not correctly been referenced in probes and ServiceMonitor
2. The name of the first (default) ingress should remain unchanged compared to chart versions < 1.2.0 to ensure updates in a running system without complications (otherwise, the "old" ingress will not be deleted by helm)
=> [sophora-image-access-service] SIMSI-127: fix usage of new metrics port; keep orginal name of the default ingress 
