subshell/helm-charts

charts/o-neko/README.md
charts/o-neko/values.yaml

I added more documentation manually and used the bitnami readme generator to add a parameters list.

[o-neko] improve o-neko chart documentation

---

charts/sophora-server/Chart.yaml
charts/sophora-server/templates/sophora-init-configmap.yaml

Changing the `replicaCount` should not alter the init script.

[sophora-server]: improve init script for staging server

---

charts/sophora-server/Chart.yaml
charts/sophora-server/values.yaml

these versions add multiplatform support for those tools

[sophora-server] update sidecar tools to latest version

---

charts/sophora-server/Chart.yaml
charts/sophora-server/alerting-runbook.md
charts/sophora-server/templates/prometheusrule.yaml
charts/sophora-server/test-values.yaml
charts/sophora-server/values.yaml

This PR adds alerting rules to the chart of the Sophora server.

[sophora-server] add alerting rules

---

charts/sophora-cluster-common/.helmignore
charts/sophora-cluster-common/Chart.yaml
charts/sophora-cluster-common/README.md
charts/sophora-cluster-common/alerting-runbook.md
charts/sophora-cluster-common/templates/_helpers.tpl
charts/sophora-cluster-common/templates/alerts/prometheusrule.yaml
charts/sophora-cluster-common/templates/extra-deploy.yaml
charts/sophora-cluster-common/templates/lb/ingress.yaml
charts/sophora-cluster-common/templates/lb/service.yaml
charts/sophora-cluster-common/templates/pdb/pdb.yaml
charts/sophora-cluster-common/test-values.yaml
charts/sophora-cluster-common/values.yaml

This chart contains common resources useful for cloud installations of Sophora.

[sophora-cluster-common] add Sophora cluster common chart

---

charts/sophora-seo-check/Chart.yaml
charts/sophora-seo-check/templates/statefulset.yaml

This PR fixes a few minor errors in the chart for Sophora SEO Check.

sophora-seo-check: minor fixes

---

charts/sophora-linkchecker/Chart.yaml
charts/sophora-linkchecker/README.md
charts/sophora-linkchecker/templates/_helpers.tpl
charts/sophora-linkchecker/templates/configmap.yaml
charts/sophora-linkchecker/templates/deployment.yaml
charts/sophora-linkchecker/templates/extra-list.yaml
charts/sophora-linkchecker/templates/ingress.yaml
charts/sophora-linkchecker/templates/service.yaml
charts/sophora-linkchecker/test-values.yaml
charts/sophora-linkchecker/values.yaml

This PR adds a new chart for the Sophora Link Checker module (not yet released.)

add chart for Sophora Link Checker

---

charts/sophora-server/Chart.yaml
charts/sophora-server/templates/statefulset.yaml
charts/sophora-server/test-values.yaml
charts/sophora-server/values.yaml

[sophora-server] add sidecars

---

charts/sophora-cluster-common/Chart.yaml
charts/sophora-cluster-common/templates/alerts/prometheusrule.yaml
charts/sophora-server/Chart.yaml
charts/sophora-server/alerting-runbook.md
charts/sophora-server/templates/prometheusrule.yaml

This changes the severity, query or duration of some alerts.

[sophora-server][sophora-cluster-common]: change some alerts

---

charts/sophora-contentapi/Chart.yaml
charts/sophora-contentapi/README.md
charts/sophora-contentapi/templates/_helpers.tpl
charts/sophora-contentapi/templates/configmap.yaml
charts/sophora-contentapi/templates/deployment.yaml
charts/sophora-contentapi/templates/extra-list.yaml
charts/sophora-contentapi/templates/ingress.yaml
charts/sophora-contentapi/templates/service.yaml
charts/sophora-contentapi/test-values.yaml
charts/sophora-contentapi/values.yaml

This PR adds a new chart for the Sophora Content API (external app).

add chart for Sophora Content API

---

charts/sophora-server/Chart.yaml
charts/sophora-server/templates/statefulset.yaml

solves https://github.com/subshell/helm-charts/issues/112

[sophora-server]: use configured HTTP port for server mode labeler

---

charts/sophora-importer/Chart.yaml
charts/sophora-importer/templates/statefulset.yaml

ZUPUS-298: remove debug output with `find` (slows down/crashes startup)

---

charts/sophora-server/Chart.yaml
charts/sophora-server/templates/statefulset.yaml
charts/sophora-server/test-values.yaml
charts/sophora-server/values.yaml

[sophora-server] add extraVolumes and extraVolumeMounts

---

charts/sophora-cluster-common/Chart.yaml
charts/sophora-cluster-common/templates/lb/ingress-grpc.yaml
charts/sophora-cluster-common/test-values.yaml
charts/sophora-cluster-common/values.yaml

same as #121 but for the cluster common chart

[sophora-cluster-common] add grpc ingress option

---

charts/sophora-media-finder/README.md
charts/sophora-media-finder/values.yaml

SMFI-51 Media-Finder Chart Documentation

---

charts/sophora-importer/Chart.yaml
charts/sophora-importer/values.yaml

Related to ZUPUS-382, SOIMI-651

[sophora-importer] fix filter in logback config (SOIMI-651)

---

charts/sophora-server/Chart.yaml
charts/sophora-server/templates/_helpers.tpl
charts/sophora-server/templates/statefulset.yaml
charts/sophora-server/test-values.yaml
charts/sophora-server/values.yaml

this is to trigger a re-deployment when the content of any configmap changes

chore: hash all configmaps and and checksum to statefulset annotation

---

charts/sophora-ugc/Chart.yaml

SUCI-810 Increase UGC helm chart version

---

charts/sophora-ugc/Chart.yaml
charts/sophora-ugc/templates/_helpers.tpl
charts/sophora-ugc/templates/deployment.yaml
charts/sophora-ugc/test-values.yaml
charts/sophora-ugc/values.yaml

Adds configuration options for extraContainers and extraInitContainers
Bumping version to 2.0.5

UNSO-1979: add initContainers to UGC

---

charts/sophora-youtube-connector/Chart.yaml
charts/sophora-youtube-connector/templates/statefulset.yaml

[sophora-youtube-connector] add checksum annotations for logback- and media-config

---

charts/sophora-ai/Chart.yaml
charts/sophora-ai/README.md
charts/sophora-ai/templates/_helpers.tpl
charts/sophora-ai/templates/configmap.yaml
charts/sophora-ai/templates/deployment.yaml
charts/sophora-ai/templates/extra-list.yaml
charts/sophora-ai/templates/ingress.yaml
charts/sophora-ai/templates/service.yaml
charts/sophora-ai/test-values.yaml
charts/sophora-ai/values.yaml

This PR adds a new chart for the Sophora AI module (not yet released.)

add chart for Sophora AI

---

charts/sophora-metadata-supplier/Chart.yaml
charts/sophora-metadata-supplier/templates/pvc.yaml
charts/sophora-metadata-supplier/tests/pvc_test.yaml
charts/sophora-metadata-supplier/tests/values/pvc-with-datasource.yaml
charts/sophora-metadata-supplier/tests/values/pvc-without-datasource.yaml
charts/sophora-metadata-supplier/values.yaml

See https://support.subshell.com/browse/ZUPUS-595

[sophora-metadata-supplier] add dataSource to PVC

---

charts/sophora-indexer/Chart.yaml
charts/sophora-indexer/templates/pvc.yaml
charts/sophora-indexer/tests/pvc_test.yaml
charts/sophora-indexer/tests/values/pvc-with-datasource.yaml
charts/sophora-indexer/tests/values/pvc-without-datasource.yaml
charts/sophora-indexer/values.yaml

See https://support.subshell.com/browse/ZUPUS-595

[sophora-indexer] add dataSource to PVC

---

charts/sophora-metadata-supplier/Chart.yaml
charts/sophora-metadata-supplier/README.md
charts/sophora-metadata-supplier/alerting-runbook.md
charts/sophora-metadata-supplier/templates/prometheusrule.yaml
charts/sophora-metadata-supplier/test-values.yaml
charts/sophora-metadata-supplier/values.yaml

[SOMSI-363](https://support.subshell.com/browse/SOMSI-363)

[sophora-metadata-supplier] prometheus alert configuration for full job queue

---

charts/sophora-metadata-supplier/Chart.yaml
charts/sophora-metadata-supplier/README.md
charts/sophora-metadata-supplier/alerting-runbook.md
charts/sophora-metadata-supplier/templates/prometheusrule.yaml
charts/sophora-metadata-supplier/test-values.yaml
charts/sophora-metadata-supplier/values.yaml

[SOMSI-363](https://support.subshell.com/browse/SOMSI-363)

[sophora-metadata-supplier] configurable values in prometheus alert configuration for full job queue
